var x=30;
var y=80;
console.log("value of x=" +x);
console.log("value of y=" +y);
var result=((x<40)&&(y<=90));
console.log("(x<40)&&(y<=90):",result);
var result=((x==50)||(y>80));
console.log("(x==50)||(y>80):",result);
var result=!((x>20)&&(y>=80));
console.log("!((x>20)&&(y>=80)):",result);